# Write your MySQL query statement below
WITH CTE AS (
    SELECT 
    ID
    , RECORDDATE
    , TEMPERATURE
    , LAG(RECORDDATE, 1, NULL) OVER (ORDER BY RECORDDATE) AS PREVIOUS_DATE
    , LAG(TEMPERATURE, 1, NULL) OVER (ORDER BY RECORDDATE) AS PREVIOUS_TEMPERATURE
    FROM WEATHER
)
SELECT ID
FROM CTE
WHERE 1=1
AND TEMPERATURE > PREVIOUS_TEMPERATURE
AND DATEDIFF(RECORDDATE, PREVIOUS_DATE) = 1