# Write your MySQL query statement below
SELECT W1.ID
FROM WEATHER W1
JOIN WEATHER W2
ON W1.RECORDDATE = DATE_ADD(W2.RECORDDATE,INTERVAL 1 DAY)
WHERE W1.TEMPERATURE > W2.TEMPERATURE

# WITH T_LAG AS (
#     SELECT
#     ID, 
#     RECORDDATE,
#     TEMPERATURE,
#     LAG(TEMPERATURE,1,TEMPERATURE) OVER (ORDER BY RECORDDATE) AS PRE_TEMP
#     FROM WEATHER
# )
# SELECT ID
# FROM T_LAG
# WHERE TEMPERATURE > PRE_TEMP