# Write your MySQL query statement below
WITH CTE AS (SELECT 
ID
, NUM
, LAG(NUM,1,0) OVER () AS PREVIOUS_NUM
, LAG(NUM,2,0) OVER() AS PREVIOUS_PREVIOUS_NUM
FROM LOGS
)
SELECT DISTINCT NUM AS ConsecutiveNums
FROM CTE
WHERE 1=1
AND NUM = PREVIOUS_NUM
AND NUM = PREVIOUS_PREVIOUS_NUM
