# Write your MySQL query statement below
WITH TOTAL_SUM AS (
    SELECT 
    VISITED_ON, SUM(AMOUNT) AS AMOUNT
    FROM CUSTOMER
    GROUP BY VISITED_ON
)
, CAL_MA7 AS (
    SELECT
    VISITED_ON
    , SUM(AMOUNT) OVER (ORDER BY VISITED_ON ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS AMOUNT
    , ROUND((SUM(AMOUNT) OVER (ORDER BY VISITED_ON ROWS BETWEEN 6 PRECEDING AND CURRENT ROW))/7,2) AS AVERAGE_AMOUNT
    , COUNT(VISITED_ON) OVER (ORDER BY VISITED_ON ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS COUNT_ROW
    FROM TOTAL_SUM
)
SELECT 
VISITED_ON
, AMOUNT
, AVERAGE_AMOUNT
FROM CAL_MA7
WHERE COUNT_ROW = 7
ORDER BY VISITED_ON