WITH CTE AS (
    SELECT VISITED_ON, SUM(AMOUNT) AS AMOUNT,
    ROW_NUMBER() OVER (ORDER BY VISITED_ON ASC) AS NUM
    FROM CUSTOMER
    GROUP BY VISITED_ON
    ORDER BY VISITED_ON ASC
)
SELECT VISITED_ON, 
SUM(AMOUNT) OVER(ORDER BY VISITED_ON ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS AMOUNT,
ROUND((SUM(AMOUNT) OVER(ORDER BY VISITED_ON ROWS BETWEEN 6 PRECEDING AND CURRENT ROW)/7),2) AS AVERAGE_AMOUNT
FROM CTE
ORDER BY VISITED_ON ASC
LIMIT 1000000 OFFSET 6