# Write your MySQL query statement below
SELECT V.CUSTOMER_ID, COUNT(*) AS COUNT_NO_TRANS
FROM VISITS V
LEFT JOIN TRANSACTIONS S 
ON V.VISIT_ID = S.VISIT_ID
WHERE S.TRANSACTION_ID IS NULL
GROUP BY V.CUSTOMER_ID