# Write your MySQL query statement below
WITH HAVE_BOSS AS (
    SELECT *
    FROM EMPLOYEES
    WHERE MANAGER_ID IS NOT NULL
)

SELECT EMPLOYEE_ID
FROM HAVE_BOSS
WHERE MANAGER_ID NOT IN (
    SELECT EMPLOYEE_ID
    FROM EMPLOYEES
)
AND SALARY < 30000
ORDER BY EMPLOYEE_ID