# Write your MySQL query statement below
WITH CTE AS (
    SELECT
    U.PRODUCT_ID, 
    ROUND(SUM(U.UNITS * P.PRICE)/SUM(U.UNITS),2) AS AVERAGE_PRICE
    FROM UNITSSOLD U
    LEFT JOIN PRICES P
    ON U.PRODUCT_ID = P.PRODUCT_ID
    AND U.PURCHASE_DATE >= P.START_DATE
    AND U.PURCHASE_DATE <= P.END_DATE
    GROUP BY U.PRODUCT_ID
)
SELECT P.PRODUCT_ID, COALESCE(C.AVERAGE_PRICE,0) AS AVERAGE_PRICE
FROM PRICES P
LEFT JOIN CTE C
ON C.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_ID