# Write your MySQL query statement below
WITH CTE AS (
    SELECT F.PRODUCT_ID
    , ROUND(SUM(D.PRICE*F.UNITS)/SUM(F.UNITS),2) AS AVERAGE_PRICE
    FROM UNITSSOLD F
    LEFT JOIN PRICES D
    ON F.PRODUCT_ID = D.PRODUCT_ID
    AND F.PURCHASE_DATE BETWEEN START_DATE AND END_DATE
    GROUP BY F.PRODUCT_ID
)
SELECT D.PRODUCT_ID, COALESCE(AVERAGE_PRICE, 0) AS AVERAGE_PRICE
FROM PRICES D
LEFT JOIN CTE C
ON C.PRODUCT_ID = D.PRODUCT_ID
GROUP BY D.PRODUCT_ID
