# Write your MySQL query statement below
WITH CTE AS (
    SELECT *
    FROM STUDENTS STU
    CROSS JOIN SUBJECTS SUB
)
SELECT C.STUDENT_ID, C.STUDENT_NAME, C.SUBJECT_NAME, COUNT(E.SUBJECT_NAME) AS ATTENDED_EXAMS
FROM CTE C 
LEFT JOIN EXAMINATIONS E
ON C.STUDENT_ID = E.STUDENT_ID
AND C.SUBJECT_NAME = E.SUBJECT_NAME
GROUP BY C.STUDENT_NAME, C.SUBJECT_NAME
ORDER BY C.STUDENT_ID, C.SUBJECT_NAME
