# Write your MySQL query statement below
SELECT 
STU.STUDENT_ID,
STU.STUDENT_NAME,
SUB.SUBJECT_NAME,
-- Count trên 1 cột cụ thể sẽ bỏ qua NULL
COUNT(E.STUDENT_ID) AS attended_exams
FROM STUDENTS STU
CROSS JOIN SUBJECTS SUB 
LEFT JOIN EXAMINATIONS E
ON STU.STUDENT_ID = E.STUDENT_ID
AND SUB.SUBJECT_NAME = E.SUBJECT_NAME
GROUP BY 
STU.STUDENT_ID,
STU.STUDENT_NAME,
SUB.SUBJECT_NAME
ORDER BY 
STU.STUDENT_ID,
SUB.SUBJECT_NAME
