# Write your MySQL query statement below
WITH CTE AS (
    SELECT *,
    MIN(YEAR) OVER (PARTITION BY PRODUCT_ID) AS FIRST_YEAR
    FROM SALES
)
SELECT PRODUCT_ID, FIRST_YEAR, QUANTITY, PRICE
FROM CTE
WHERE YEAR = FIRST_YEAR
