# Write your MySQL query statement below
WITH CTE AS (
SELECT *
, CAST('2019-07-27' AS DATE) AS PERIOD_END
, DATE_SUB(CAST('2019-07-27' AS DATE), INTERVAL 29 DAY) AS PERIOD_START
FROM ACTIVITY
)
SELECT ACTIVITY_DATE AS DAY, COUNT(DISTINCT USER_ID) AS ACTIVE_USERS
FROM CTE
WHERE 1=1
AND ACTIVITY_DATE BETWEEN PERIOD_START AND PERIOD_END
GROUP BY ACTIVITY_DATE
