# Write your MySQL query statement below
WITH FIRST_LOGIN AS (
    SELECT PLAYER_ID, MIN(EVENT_DATE) AS FIRST_LOGIC
    FROM ACTIVITY
    GROUP BY PLAYER_ID
)
, CALCULATE_PREVIOUS AS (
    SELECT *
    ,DATE_SUB(EVENT_DATE, INTERVAL 1 DAY) AS PREVIOUS_DATE
    FROM ACTIVITY
)
, JOIN_OUTPUT AS (
    SELECT C.PLAYER_ID, F.FIRST_LOGIC, C.PREVIOUS_DATE
    FROM CALCULATE_PREVIOUS C
    LEFT JOIN FIRST_LOGIN F
    ON C.PLAYER_ID = F.PLAYER_ID
)
SELECT ROUND(SUM(FIRST_LOGIC = PREVIOUS_DATE)/COUNT(DISTINCT PLAYER_ID),2) AS FRACTION
FROM JOIN_OUTPUT