# Write your MySQL query statement below
SELECT 
LEFT(TRANS_DATE,7) AS MONTH
, COUNTRY
, COUNT(*) AS TRANS_COUNT
, SUM(STATE = 'approved') AS APPROVED_COUNT
, SUM(AMOUNT) AS TRANS_TOTAL_AMOUNT
, SUM((STATE = 'approved')*AMOUNT) AS APPROVED_TOTAL_AMOUNT
FROM TRANSACTIONS
GROUP BY LEFT(TRANS_DATE,7), COUNTRY