# Write your MySQL query statement below
SELECT
LEFT(TRANS_DATE,7) AS MONTH,
COUNTRY,
COUNT(ID) AS TRANS_COUNT,
COUNT(CASE WHEN STATE = 'approved' THEN 1 ELSE NULL END) AS APPROVED_COUNT,
SUM(AMOUNT) AS TRANS_TOTAL_AMOUNT,
SUM(CASE WHEN STATE = 'approved' THEN AMOUNT ELSE 0 END) AS APPROVED_TOTAL_AMOUNT
FROM TRANSACTIONS
GROUP BY 
LEFT(TRANS_DATE,7),
COUNTRY 