# Write your MySQL query statement below
WITH CREATE_INIT AS (
SELECT DISTINCT PRODUCT_ID
, 10 AS NEW_PRICE
, CAST('2000-01-01' AS DATE) AS CHANGE_DATE
FROM PRODUCTS
UNION
SELECT *
FROM PRODUCTS
)
, CTE AS (
SELECT *
, LEAD(CHANGE_DATE,1,CAST('2999-12-31' AS DATE)) OVER (PARTITION BY PRODUCT_ID ORDER BY CHANGE_DATE) AS NEXT_CHANGE
FROM CREATE_INIT
)
SELECT PRODUCT_ID, NEW_PRICE AS PRICE
FROM CTE C
WHERE 1=1
AND CAST('2019-08-16' AS DATE) >= CHANGE_DATE
AND CAST('2019-08-16' AS DATE) < NEXT_CHANGE
