# Write your MySQL query statement below
WITH CTE AS (
    SELECT D1.CUSTOMER_ID
    , CASE
    WHEN (MIN(D1.ORDER_DATE) = MIN(D2.CUSTOMER_PREF_DELIVERY_DATE)) THEN 1
    ELSE 0
    END AS FLAG_IMMEDIATE
    FROM DELIVERY D1
    JOIN DELIVERY D2
    ON D1.DELIVERY_ID = D2.DELIVERY_ID
    GROUP BY D1.CUSTOMER_ID
)
SELECT ROUND(SUM(FLAG_IMMEDIATE)/COUNT(*)*100,2) AS IMMEDIATE_PERCENTAGE
FROM CTE