# Write your MySQL query statement below
WITH CTE AS (
    SELECT
    *,
    ROW_NUMBER() OVER (PARTITION BY CUSTOMER_ID ORDER BY ORDER_DATE) AS NUM
    FROM DELIVERY 
)
SELECT 
ROUND(SUM(CASE WHEN ORDER_DATE = CUSTOMER_PREF_DELIVERY_DATE THEN 1 ELSE 0 END)/COUNT(CUSTOMER_ID)*100,2) AS IMMEDIATE_PERCENTAGE
FROM CTE
WHERE NUM = 1

