# Write your MySQL query statement below
WITH CALCULATE AS (
    SELECT 
    QUERY_NAME
    , RESULT
    , (RATING/POSITION) AS QUALITY
    , COUNT(*) OVER (PARTITION BY QUERY_NAME) AS PARTITION_TOTAL
    FROM QUERIES
)
, COUNT_POOR_RATING AS (
    SELECT QUERY_NAME, COUNT(*) AS POOR_RATING
    FROM QUERIES
    WHERE 1=1
    AND RATING < 3
    GROUP BY QUERY_NAME
)
SELECT 
Q.QUERY_NAME
, ROUND(SUM(C.QUALITY)/C.PARTITION_TOTAL,2) AS QUALITY
, ROUND(COALESCE(P.POOR_RATING,0)/C.PARTITION_TOTAL*100,2) AS POOR_QUERY_PERCENTAGE
FROM QUERIES Q
LEFT JOIN COUNT_POOR_RATING P
ON Q.QUERY_NAME = P.QUERY_NAME
JOIN CALCULATE C
ON Q.QUERY_NAME = C.QUERY_NAME
AND Q.RESULT = C.RESULT
GROUP BY Q.QUERY_NAME
