# Write your MySQL query statement below
SELECT
QUERY_NAME,
ROUND((SUM(RATING/POSITION))/COUNT(QUERY_NAME),2) AS QUALITY,
ROUND(COUNT(CASE WHEN RATING < 3 THEN 1 ELSE NULL END)/COUNT(QUERY_NAME)*100,2) AS POOR_QUERY_PERCENTAGE
FROM QUERIES
GROUP BY QUERY_NAME
