# Write your MySQL query statement below
SELECT 
PRODUCT_NAME,
SUM(UNIT) AS UNIT
FROM ORDERS O
LEFT JOIN PRODUCTS P
ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE 1=1
AND LEFT(ORDER_DATE, 7) = '2020-02'
GROUP BY LEFT(ORDER_DATE, 7), PRODUCT_NAME
HAVING SUM(UNIT) >= 100
