# Write your MySQL query statement below
WITH CTE_TOTAL AS (
    SELECT USER_ID, COUNT(*) AS TOTAL_ACTION
    FROM CONFIRMATIONS
    GROUP BY USER_ID
)
, CTE_CONFIRM AS(
    SELECT USER_ID, COUNT(*) AS CONFIRMED_ACTION
    FROM CONFIRMATIONS
    WHERE 1=1
    AND ACTION = 'confirmed'
    GROUP BY USER_ID
)
SELECT 
S.USER_ID
, ROUND(COALESCE(C2.CONFIRMED_ACTION,0) / COALESCE(C1.TOTAL_ACTION,1), 2) AS CONFIRMATION_RATE
FROM SIGNUPS S
LEFT JOIN CTE_TOTAL C1
ON S.USER_ID = C1.USER_ID
LEFT JOIN CTE_CONFIRM C2
ON S.USER_ID = C2.USER_ID
GROUP BY S.USER_ID

