# Write your MySQL query statement below
WITH CTE AS (
    SELECT 
    SALARY,
    DENSE_RANK() OVER (ORDER BY SALARY DESC) AS RNK
    FROM EMPLOYEE
)
SELECT MAX(SALARY) AS SECONDHIGHESTSALARY
FROM CTE
WHERE RNK = 2