# Write your MySQL query statement below
WITH CTE AS (
SELECT 
D.NAME AS DEPARTMENT
, E.NAME AS EMPLOYEE
, E.SALARY
, DENSE_RANK() OVER (PARTITION BY E.DEPARTMENTID ORDER BY E.SALARY DESC) AS HIGH_EARNERS
FROM EMPLOYEE E 
LEFT JOIN DEPARTMENT D
ON E.DEPARTMENTID = D.ID
)
SELECT DEPARTMENT, EMPLOYEE, SALARY
FROM CTE
WHERE 1=1
AND HIGH_EARNERS <= 3