# Write your MySQL query statement below
SELECT A1.MACHINE_ID, ROUND(AVG((A2.TIMESTAMP - A1.TIMESTAMP)),3) AS PROCESSING_TIME
FROM ACTIVITY A1
LEFT JOIN (
    SELECT MACHINE_ID, PROCESS_ID, TIMESTAMP
    FROM ACTIVITY
    WHERE 1=1
    AND ACTIVITY_TYPE = 'end'
) A2
ON A1.MACHINE_ID = A2.MACHINE_ID
AND A1.PROCESS_ID = A2.PROCESS_ID
WHERE 1=1
AND ACTIVITY_TYPE = 'start'
GROUP BY MACHINE_ID


