# Write your MySQL query statement below
WITH CTE AS (
    SELECT A1.MACHINE_ID, A1.PROCESS_ID, A1.TIMESTAMP AS START, A2.TIMESTAMP AS END
    FROM ACTIVITY A1
    JOIN ACTIVITY A2
    ON A1.MACHINE_ID = A2.MACHINE_ID
    AND A1.PROCESS_ID = A2.PROCESS_ID
    AND A1.ACTIVITY_TYPE = 'start'
    AND A2.ACTIVITY_TYPE = 'end'
)
SELECT MACHINE_ID, 
ROUND(SUM(END-START)/COUNT(PROCESS_ID),3) AS PROCESSING_TIME
FROM CTE
GROUP BY MACHINE_ID


