# Write your MySQL query statement below
WITH TOTAL_USER AS (
    SELECT COUNT(*) AS TOTAL_USER
    FROM USERS
)
SELECT 
R.CONTEST_ID,
ROUND(COUNT(R.USER_ID)/(SELECT TOTAL_USER FROM TOTAL_USER)*100,2) AS PERCENTAGE
FROM REGISTER R
LEFT JOIN USERS U
ON R.USER_ID = U.USER_ID
GROUP BY R.CONTEST_ID
ORDER BY PERCENTAGE DESC, CONTEST_ID ASC
