# Write your MySQL query statement below
SELECT * FROM (
SELECT DISTINCT
R.CONTEST_ID
, ROUND(COUNT(*) OVER (PARTITION BY R.CONTEST_ID) / (SELECT COUNT(*) FROM USERS) * 100,2) AS PERCENTAGE 
FROM REGISTER R
LEFT JOIN USERS U
ON R.USER_ID = U.USER_ID
) A
ORDER BY PERCENTAGE DESC, CONTEST_ID ASC
