# Write your MySQL query statement below
SELECT USER_ID AS ID, SUM(NUM_FEN) AS NUM
FROM (
SELECT REQUESTER_ID AS USER_ID, COUNT(*) AS NUM_FEN
FROM REQUESTACCEPTED
GROUP BY REQUESTER_ID
UNION ALL
SELECT ACCEPTER_ID AS USER_ID, COUNT(*) AS NUM_FEN
FROM REQUESTACCEPTED
GROUP BY ACCEPTER_ID
) AS T
GROUP BY USER_ID
ORDER BY NUM DESC
LIMIT 1
